version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    networks:
      - app-network
    ports:
      - 5672:5672
      - 15672:15672

  stock-service:
    image: deliverymuch/backend-challenge:stock-service
    networks:
      - app-network
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    restart: on-failure

  # stock-control-api:
  #   build: ./
  #   entrypoint: ./.docker/entrypoint.sh
  #   container_name: stock-control-api
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   ports:
  #     - 3001:3000
  #   volumes:
  #     - ./:/home/node/express
  #   networks:
  #     - app-network
  #     - db-network
  #     - cache-network
  #   depends_on:
  #     - rabbitmq
  #     - mongo-db
  #     - redis

  mongo-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: arthur
      MONGO_INITDB_ROOT_PASSWORD: arthur
    ports:
      - 27017:27017
    volumes:
      - ./database/:/data/db
    networks:
      - db-network

  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - cache-network


networks:
  app-network:
    driver: bridge
  db-network:
    driver: bridge
  cache-network:
    driver: bridge
